name: "Prune container images"

on:
  workflow_dispatch:
  schedule:
    - cron: "47 12 * * *"

permissions:
  packages: read
  contents: read

jobs:
  prune-container-images:
    uses: nrkno/sofie-nrk-github-workflows/.github/workflows/prune-container-images.yml@745e7d92d46ab3873739c51e6ac5ab158c941851 # main
    with:
      dry-run: false
      prune-untagged: true
      package-name: sofie-monitor
    secrets:
      prune-token: ${{ secrets.GHCR_PRUNE_TOKEN }}
